import "../fonts/SF-UI-Display-Regular.otf"
import "../fonts/SF-UI-Display-Bold.otf"
import "../fonts/SF-UI-Display-Heavy.otf"
import "../fonts/SF-UI-Display-Light.otf"
import "../fonts/SF-UI-Display-Medium.otf"
import "../fonts/SF-UI-Display-Semibold.otf"
import "../fonts/SF-UI-Display-Black.otf"
